"""Seed data for Amara Bali Villas."""

VILLAS = [
    {
        "id": "villa-suara-canggu",
        "slug": "villa-suara-canggu",
        "name": "Villa Suara",
        "location": "Canggu",
        "category": "luxury",
        "type": "Luxury Villa",
        "price_per_night": 685.0,
        "rating": 4.95,
        "reviews_count": 128,
        "bedrooms": 4,
        "bathrooms": 4,
        "guests": 8,
        "pool": True,
        "wifi": True,
        "short_description": "An architectural sanctuary set against rice terraces with a 20-metre infinity pool overlooking the ocean.",
        "description": "Villa Suara is a private architectural retreat tucked behind ironwood gates in Berawa, Canggu. Four open-plan suites flow seamlessly into the tropical garden, anchored by a 20-metre infinity pool that catches the sunset over the Indian Ocean. The villa is staffed by a private chef, butler and housekeeping team, ensuring every detail is considered before you arrive.",
        "amenities": ["Private Infinity Pool", "Private Chef", "Butler Service", "Air Conditioning", "WiFi", "Smart TV", "Outdoor Cinema", "Yoga Pavilion", "Spa Room", "Gym"],
        "images": [
            "https://images.unsplash.com/photo-1728049006562-236e5b0dddea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1728049006363-f8e583040180?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1601086540476-7d9fa9dd6023?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1521783593447-5702b9bfd267?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.6500,
        "lng": 115.1383,
        "featured": True,
    },
    {
        "id": "villa-ombak-seminyak",
        "slug": "villa-ombak-seminyak",
        "name": "Villa Ombak",
        "location": "Seminyak",
        "category": "beachfront",
        "type": "Beachfront Villa",
        "price_per_night": 920.0,
        "rating": 4.92,
        "reviews_count": 96,
        "bedrooms": 5,
        "bathrooms": 5,
        "guests": 10,
        "pool": True,
        "wifi": True,
        "short_description": "Direct beachfront with uninterrupted sunset views, white-sand garden and a 25m lap pool.",
        "description": "Villa Ombak sits directly on the powdery shores of Seminyak with the Indian Ocean as its backyard. Five spacious suites are arranged around a 25-metre saltwater pool, with the open-air living pavilion just steps from the sand. Sunsets here are an event — and our team can curate a private dinner on the beach to mark them.",
        "amenities": ["Beachfront Access", "25m Lap Pool", "Private Chef", "Butler Service", "WiFi", "Smart TV", "Beach Cabana", "Wine Cellar", "Spa Room"],
        "images": [
            "https://images.unsplash.com/photo-1714890513996-314128ed05b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1662950267280-0cdf5f7139b4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1721050739056-fb12f9663f23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.6900,
        "lng": 115.1633,
        "featured": True,
    },
    {
        "id": "villa-padma-ubud",
        "slug": "villa-padma-ubud",
        "name": "Villa Padma",
        "location": "Ubud",
        "category": "retreat",
        "type": "Retreat Villa",
        "price_per_night": 540.0,
        "rating": 4.97,
        "reviews_count": 211,
        "bedrooms": 3,
        "bathrooms": 3,
        "guests": 6,
        "pool": True,
        "wifi": True,
        "short_description": "Suspended above the Ayung river valley with private yoga pavilion and resident wellness curator.",
        "description": "Set deep in the jungles of Payangan, Villa Padma is an open-air sanctuary cantilevered over the Ayung river. Three private suites overlook the canopy, while a teakwood yoga shala plays host to morning practice with our resident wellness curator. The villa includes a daily ceremonial breakfast and a curated apothecary in every bathroom.",
        "amenities": ["Private Pool", "Yoga Pavilion", "Wellness Curator", "Private Chef", "WiFi", "Outdoor Bath", "River View", "Meditation Garden"],
        "images": [
            "https://images.unsplash.com/photo-1644205840798-4ad8e4b8cab1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1518860308377-800f02d5498a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1581859814481-bfd944e3122f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.4555,
        "lng": 115.2552,
        "featured": True,
    },
    {
        "id": "villa-cinta-jimbaran",
        "slug": "villa-cinta-jimbaran",
        "name": "Villa Cinta",
        "location": "Jimbaran",
        "category": "honeymoon",
        "type": "Honeymoon Villa",
        "price_per_night": 780.0,
        "rating": 4.98,
        "reviews_count": 73,
        "bedrooms": 1,
        "bathrooms": 2,
        "guests": 2,
        "pool": True,
        "wifi": True,
        "short_description": "A clifftop one-bedroom hideaway with private plunge pool and a floor-to-ceiling ocean window.",
        "description": "Designed exclusively for two, Villa Cinta is perched on the limestone cliffs of Jimbaran with sweeping views of the bay. The single bedroom suite opens onto a private plunge pool and outdoor rain-shower. Floating breakfasts, candlelit dinners on the rocks, and a couple's spa ritual are included in your stay.",
        "amenities": ["Private Plunge Pool", "Ocean Cliff View", "Floating Breakfast", "Couple's Spa", "Private Chef", "WiFi", "Outdoor Rain Shower"],
        "images": [
            "https://images.unsplash.com/photo-1721050739056-fb12f9663f23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1728051104796-a8c0f667cd90?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.7900,
        "lng": 115.1600,
        "featured": True,
    },
    {
        "id": "villa-laut-canggu",
        "slug": "villa-laut-canggu",
        "name": "Villa Laut",
        "location": "Canggu",
        "category": "family",
        "type": "Family Villa",
        "price_per_night": 495.0,
        "rating": 4.88,
        "reviews_count": 154,
        "bedrooms": 5,
        "bathrooms": 5,
        "guests": 12,
        "pool": True,
        "wifi": True,
        "short_description": "A family-friendly compound with shallow kids pool, games room and a 12-seat dining pavilion.",
        "description": "Villa Laut welcomes families with five generously proportioned bedrooms, two of which connect through a shared playroom. The garden hosts a main pool with shallow kids' end, an outdoor cinema, and a dedicated games pavilion. Childcare and chef services are arranged at request.",
        "amenities": ["Family Pool", "Kids Pool", "Games Pavilion", "Outdoor Cinema", "Private Chef", "Babysitter on Request", "WiFi", "Library"],
        "images": [
            "https://images.unsplash.com/photo-1601086540476-7d9fa9dd6023?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1728049006363-f8e583040180?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.6470,
        "lng": 115.1410,
        "featured": False,
    },
    {
        "id": "villa-melati-seminyak",
        "slug": "villa-melati-seminyak",
        "name": "Villa Melati",
        "location": "Seminyak",
        "category": "wedding",
        "type": "Wedding Villa",
        "price_per_night": 1250.0,
        "rating": 4.96,
        "reviews_count": 64,
        "bedrooms": 6,
        "bathrooms": 7,
        "guests": 14,
        "pool": True,
        "wifi": True,
        "short_description": "A wedding estate with frangipani gardens, ceremonial pavilion and seating for 120 guests.",
        "description": "Villa Melati is purpose-built for celebrations. The estate features a sweeping lawn for ceremonies, a teak pavilion that seats 120 for dinner, and a separate residence for the bridal party. Our wedding curator takes care of every element — from florist to band — so the families can simply enjoy the moment.",
        "amenities": ["Ceremonial Lawn", "Teak Pavilion (120 seats)", "Bridal Suite", "Wedding Curator", "Private Chef", "Wine Cellar", "Spa Room", "WiFi"],
        "images": [
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1521783593447-5702b9bfd267?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1714890513996-314128ed05b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.6920,
        "lng": 115.1670,
        "featured": False,
    },
    {
        "id": "villa-anyar-uluwatu",
        "slug": "villa-anyar-uluwatu",
        "name": "Villa Anyar",
        "location": "Uluwatu",
        "category": "luxury",
        "type": "Luxury Villa",
        "price_per_night": 1100.0,
        "rating": 4.94,
        "reviews_count": 48,
        "bedrooms": 4,
        "bathrooms": 5,
        "guests": 8,
        "pool": True,
        "wifi": True,
        "short_description": "A modernist clifftop villa with 30m horizon-edge pool overlooking Padang Padang beach.",
        "description": "Villa Anyar is a study in restraint — board-formed concrete, weathered teak, and an unbroken horizon. The 30-metre pool drops away into a view of Padang Padang and Bingin beaches below. Each of the four suites has its own outdoor bath. A private path leads to the surf at low tide.",
        "amenities": ["30m Horizon Pool", "Cliff Access to Beach", "Private Chef", "WiFi", "Outdoor Baths", "Wine Cellar", "Sunset Bar"],
        "images": [
            "https://images.unsplash.com/photo-1728049006562-236e5b0dddea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1721050739056-fb12f9663f23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1601086540476-7d9fa9dd6023?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.8155,
        "lng": 115.0860,
        "featured": True,
    },
    {
        "id": "villa-gita-ubud",
        "slug": "villa-gita-ubud",
        "name": "Villa Gita",
        "location": "Ubud",
        "category": "honeymoon",
        "type": "Honeymoon Villa",
        "price_per_night": 620.0,
        "rating": 4.91,
        "reviews_count": 87,
        "bedrooms": 2,
        "bathrooms": 2,
        "guests": 4,
        "pool": True,
        "wifi": True,
        "short_description": "Two private bale suites surrounded by emerald rice terraces with a stone-edged plunge pool.",
        "description": "Villa Gita is woven into the rice terraces of Tegallalang, with two open-plan bale suites linked by a stone path through frangipani. The villa includes a private plunge pool, an outdoor kitchen, and a small library of regional cookbooks. Ideal for couples or close friends seeking quiet time in nature.",
        "amenities": ["Plunge Pool", "Rice Terrace View", "Private Chef", "WiFi", "Outdoor Kitchen", "Library"],
        "images": [
            "https://images.unsplash.com/photo-1644205840798-4ad8e4b8cab1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1518860308377-800f02d5498a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "lat": -8.4310,
        "lng": 115.2790,
        "featured": False,
    },
]

CATEGORIES = [
    {"slug": "luxury", "name": "Luxury Villas", "description": "Architecturally designed estates with full private staff.", "image": "https://images.unsplash.com/photo-1728049006562-236e5b0dddea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "beachfront", "name": "Beachfront Villas", "description": "Direct ocean access with sand at your doorstep.", "image": "https://images.unsplash.com/photo-1714890513996-314128ed05b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "family", "name": "Family Villas", "description": "Spacious compounds for multi-generational stays.", "image": "https://images.unsplash.com/photo-1601086540476-7d9fa9dd6023?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "honeymoon", "name": "Honeymoon Villas", "description": "Intimate retreats designed exclusively for two.", "image": "https://images.unsplash.com/photo-1721050739056-fb12f9663f23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "wedding", "name": "Wedding Villas", "description": "Estates with ceremonial pavilions and event grounds.", "image": "https://images.unsplash.com/photo-1582719508461-905c673771fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "retreat", "name": "Retreat Villas", "description": "Wellness sanctuaries with yoga shalas and curators.", "image": "https://images.unsplash.com/photo-1644205840798-4ad8e4b8cab1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
]

DESTINATIONS = [
    {"slug": "canggu", "name": "Canggu Villas", "description": "Surf breaks, beach clubs, and a creative community living between rice paddies and the ocean.", "image": "https://images.unsplash.com/photo-1662950267280-0cdf5f7139b4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "seminyak", "name": "Seminyak Villas", "description": "A polished beachside enclave known for its restaurants, ateliers and sunset rituals.", "image": "https://images.unsplash.com/photo-1714890513996-314128ed05b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "ubud", "name": "Ubud Villas", "description": "Rice terraces, river valleys and the cultural heart of Bali, set deep in the highlands.", "image": "https://images.unsplash.com/photo-1644205840798-4ad8e4b8cab1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "jimbaran", "name": "Jimbaran Villas", "description": "Limestone cliffs, fishing bays and seafood pavilions on Bali's southern peninsula.", "image": "https://images.unsplash.com/photo-1581859814481-bfd944e3122f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
]

EXPERIENCES = [
    {"id": "private-chef", "name": "Private Chef", "description": "A resident chef designs a daily menu around the morning's market run, with options for traditional Balinese, modern Indonesian or European cuisine.", "image": "https://images.unsplash.com/photo-1559339352-11d035aa65de?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 180.0},
    {"id": "airport-transfer", "name": "Airport Transfer", "description": "Private SUV with a Balinese host, cold towels and a welcome basket from Ngurah Rai International Airport.", "image": "https://images.unsplash.com/photo-1605235186583-a18036ed5fe8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 65.0},
    {"id": "floating-breakfast", "name": "Floating Breakfast", "description": "A signature Bali ritual — tropical fruits, pastries, eggs and fresh juices arranged on a wooden tray that floats on your private pool.", "image": "https://images.unsplash.com/photo-1728051104796-a8c0f667cd90?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 75.0},
    {"id": "bali-tours", "name": "Bali Tours", "description": "Curated day journeys with a private guide — temple at sunrise, water palaces, hidden waterfalls or the artisan villages of Tegallalang.", "image": "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 220.0},
    {"id": "yoga-retreat", "name": "Yoga & Meditation", "description": "Private sessions with our resident teachers in a riverside shala — vinyasa flows, sound healing or sunrise meditation.", "image": "https://images.unsplash.com/photo-1518611012118-696072aa579a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 110.0},
    {"id": "spa-wellness", "name": "Spa & Wellness", "description": "In-villa Balinese massage, body scrubs, herbal compresses and bathing rituals using local botanicals.", "image": "https://images.unsplash.com/photo-1518860308377-800f02d5498a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 140.0},
    {"id": "romantic-dinner", "name": "Romantic Dinner Setup", "description": "Candlelit dinner on the beach or in a flower-strewn garden, complete with private musicians and a four-course tasting menu.", "image": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 320.0},
    {"id": "scooter-rental", "name": "Scooter Rental", "description": "Premium scooters delivered and collected at the villa, with helmets, a route map and 24/7 roadside support.", "image": "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200", "price_from": 18.0},
]

TESTIMONIALS = [
    {"name": "Eloise & Marc Thibault", "country": "Paris, France", "rating": 5, "photo": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=srgb&fm=jpg&q=85&w=400", "review": "We spent ten days at Villa Cinta for our honeymoon and the team thought of every detail before we did. The floating breakfasts, the chef's nightly menu, the sunset ritual — it felt like a film we had stepped into."},
    {"name": "Aarav Mehta", "country": "Mumbai, India", "rating": 5, "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=85&w=400", "review": "Booked Villa Laut for our extended family of twelve and it accommodated everyone — from the toddlers to the grandparents — with grace. Our concierge Made was nothing short of magical."},
    {"name": "Sophia Lindqvist", "country": "Stockholm, Sweden", "rating": 5, "photo": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&q=85&w=400", "review": "Villa Padma in Ubud is the most considered space I have stayed in. Mornings began with cacao ceremonies in the shala and ended in candle-lit baths overlooking the canopy. Already planning my return."},
    {"name": "James & Adaeze Okafor", "country": "London, UK", "rating": 5, "photo": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?crop=entropy&cs=srgb&fm=jpg&q=85&w=400", "review": "We held our wedding at Villa Melati and it remains the most beautiful day of our lives. The wedding curator handled florists, the band, our 90 guests — flawlessly. Our families still talk about the dinner."},
]

BLOG_POSTS = [
    {
        "slug": "best-areas-to-stay-in-bali",
        "title": "The Definitive Guide to the Best Areas to Stay in Bali",
        "category": "Travel Guide",
        "excerpt": "From the surf-meets-jungle bohemia of Canggu to the cliff-top elegance of Uluwatu, here is our considered guide to where to lay your hat.",
        "cover": "https://images.unsplash.com/photo-1662950267280-0cdf5f7139b4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "author": "Maya Wirawan",
        "author_role": "Travel Editor",
        "read_time": 9,
        "date": "2026-01-12",
        "content": "Bali is a study in micro-climates and micro-cultures. To choose Canggu over Ubud, or Seminyak over Jimbaran, is to choose an entire mood for your stay.\n\n## Canggu — Surf, Cafes & Creative Culture\nA decade ago Canggu was a sleepy stretch of paddy fields punctuated by surf breaks. Today it remains low-rise and easy on the eye, but those same paddies now thread between specialty coffee bars, ceramic studios and minimalist beach clubs.\n\n## Seminyak — Polished & Coastal\nSeminyak is Bali at its most cosmopolitan. The sunsets here are an institution, the dining scene is fiercely good, and the boutiques rival those of any global capital.\n\n## Ubud — Highland & Soulful\nUbud sits at the cultural heart of the island, surrounded by terraced rice paddies and the Ayung river valley. Mornings here are slow — temples open at first light, dancers practice in courtyards, and yoga shalas fill before breakfast.\n\n## Jimbaran & Uluwatu — Cliffs & Sea\nThe southern peninsula is defined by its limestone cliffs and quiet bays. Jimbaran is famed for its seafood pavilions on the sand, while Uluwatu is the home of cliff-top villas, world-class surf and one of the island's most spiritual temples."
    },
    {
        "slug": "luxury-villa-travel-tips",
        "title": "Twelve Quiet Tips for a Luxury Villa Stay in Bali",
        "category": "Travel Tips",
        "excerpt": "What we have learned from a thousand check-ins — small rituals and quiet considerations that elevate a private villa stay.",
        "cover": "https://images.unsplash.com/photo-1728049006363-f8e583040180?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "author": "Wayan Suparta",
        "author_role": "Head of Hospitality",
        "read_time": 6,
        "date": "2026-01-04",
        "content": "Renting a villa is not the same as staying at a hotel. The villa is yours; the staff are guests in your space, and the rhythm of the day is what you make it.\n\n## Plan an Arrival Ritual\nA welcome dinner on the first night sets the tone. Brief your chef before you arrive — dietary preferences, favourite cuisines, a glass of cold rosé waiting on the deck.\n\n## Embrace the Slowness\nBali rewards stillness. Block out one full day with no plan beyond moving between the pool, the shala and the dinner table.\n\n## Use the Concierge Generously\nFrom restaurant reservations at the impossibly booked Mason or Locavore, to private surf lessons at dawn — the concierge is your shortcut to the island's best."
    },
    {
        "slug": "bali-honeymoon-guide",
        "title": "A Honeymoon Itinerary for Bali — Two Weeks, Slowly",
        "category": "Honeymoon",
        "excerpt": "A fortnight on the island, told in three chapters: the highlands, the cliffs and the sea.",
        "cover": "https://images.unsplash.com/photo-1721050739056-fb12f9663f23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "author": "Putu Ayu",
        "author_role": "Travel Curator",
        "read_time": 8,
        "date": "2025-12-22",
        "content": "Two weeks is the right length for a Bali honeymoon. Long enough to slow down, short enough to feel intentional.\n\n## Days 1–5 — Ubud\nBegin in the highlands. Stay at Villa Padma or Villa Gita. Mornings of yoga, afternoons by the river, dinners by candlelight in your shala.\n\n## Days 6–10 — Uluwatu\nMove to the cliffs. Villa Anyar or Villa Cinta. Sunsets from the pool, dinner on the rocks at La Brisa, an evening at Single Fin.\n\n## Days 11–14 — Canggu or Seminyak\nEnd by the sea. Villa Suara or Villa Ombak. Easy days, beach clubs at sunset, a private chef's tasting menu on the final night."
    },
    {
        "slug": "best-restaurants-in-canggu",
        "title": "Where We Eat in Canggu — A Local's List",
        "category": "Food & Drink",
        "excerpt": "From open-fire grills to natural wine bars and the noodle stalls our staff queue at on their day off.",
        "cover": "https://images.unsplash.com/photo-1559339352-11d035aa65de?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "author": "Made Suarjana",
        "author_role": "Concierge Lead",
        "read_time": 7,
        "date": "2025-12-10",
        "content": "Canggu is, quietly, one of the great eating neighbourhoods in Asia. These are the places we send our guests — and where you will find our staff on their day off.\n\n## Open Fire & Pavilion\n**La Baracca** for Roman pasta and tomato salads. **Mason** for theatrical tasting menus. **Penny Lane** for slow-cooked English Sundays.\n\n## Beachside\n**La Brisa** at sunset. **The Lawn** for Bloody Marys with your toes in the sand.\n\n## Local & Quiet\n**Warung Bu Mi** for the best babi guling on the strip. **Pasar Senggol** at Tanah Lot at dusk for grilled corn and skewers."
    },
    {
        "slug": "things-to-do-in-ubud",
        "title": "Twelve Things To Do in Ubud (Beyond the Obvious)",
        "category": "Travel Guide",
        "excerpt": "Past the monkey forest and the rice terrace selfies, these are the rituals our guests return for.",
        "cover": "https://images.unsplash.com/photo-1644205840798-4ad8e4b8cab1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "author": "Maya Wirawan",
        "author_role": "Travel Editor",
        "read_time": 8,
        "date": "2025-11-28",
        "content": "Ubud is more than the headline sights. Beyond the rice terraces and the monkey forest, the real Ubud unfolds slowly.\n\n## Sunrise at Pura Tirta Empul\nArrive before the crowds for the sacred springs. Wear a sarong, follow a local priest through the bathing ritual.\n\n## Cooking Class with Chef Wayan\nA half-day in a family compound — market visit, rice harvest, then a long lunch under a thatched bale.\n\n## Sound Healing at Pyramids of Chi\nA two-hour journey through gongs, bowls and chant in a giant copper pyramid. Trust us."
    },
    {
        "slug": "wedding-venues-bali",
        "title": "Choosing a Wedding Villa in Bali — A Quiet Field Guide",
        "category": "Weddings",
        "excerpt": "What we have learned curating villa weddings over fifteen years — on light, on flowers, on guest counts and on the timing of toasts.",
        "cover": "https://images.unsplash.com/photo-1582719508461-905c673771fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "author": "Kadek Pradnyani",
        "author_role": "Wedding Curator",
        "read_time": 10,
        "date": "2025-11-15",
        "content": "A villa wedding is a singular thing. The grounds are yours for two or three days; the family stays under one roof; the rhythm is unhurried.\n\n## On Light\nBali sits seven degrees south of the equator. Sunset is at six, sharp, year-round. Plan ceremonies for 4:30pm — golden light, cool air, dinner under stars.\n\n## On Flowers\nFrangipani, ginger lilies and heliconia from the morning market. Local florist Wirja in Petitenget is a quiet master.\n\n## On Guest Counts\nVilla Melati seats 120 at a long teak table. For larger weddings we curate adjacent estates — ask about our Compound Programme."
    },
]
